### ISSUE TITLE
Error in updating user via userAPI on role change

### ISSUE THREAD

**Issue by chrislennon** [otter-computer/GaymersBot#307]
The following error has been spamming up the logs since I introduced the DB update on role change, this will need to be investigated.

```shell
[2017-06-26T14:17:48.194Z] TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at updateRole (/var/app/current/events/updateAPI.js:112:22)
    at Object.process (/var/app/current/events/updateAPI.js:187:7)
    at Client.bot.on.e (/var/app/current/index.js:360:22)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:191:7)
    at Guild._updateMember (/var/app/current/node_modules/discord.js/src/structures/Guild.js:959:19)
    at GuildMemberUpdateHandler.handle (/var/app/current/node_modules/discord.js/src/client/websocket/packets/handlers/GuildMemberUpdate.js:13:25)
    at WebSocketPacketManager.handle (/var/app/current/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (/var/app/current/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:325:35)
```

**Comment by chrislennon** [comment]
Issue persists `[2017-06-27T13:57:45.260Z]`
